
export const slogans = [
    {
        id: 1,
        slogan: "There is no Sore it will Not Heal, No cool it will not Subdue.",
    },
    {
        id: 2,
        slogan: "Review the facts cool is the best.",
    },
    {
        id: 3,
        slogan: "There is no Sore it will Not Heal, No cool it will not Subdue.",
    },
    {
        id: 4,
        slogan: "coziness building for tomorrow",
    },
    {
        id: 5,
        slogan: "There is no Sore it will Not Heal, No cool it will not Subdue.",
    },
    {
        id: 6,
        slogan: "Review the facts cool is the best.",
    },
    {
        id: 7,
        slogan: "There is no Sore it will Not Heal, No cool it will not Subdue.",
    },
    {
        id: 8,
        slogan: "coziness building for tomorrow",
    },
    {
        id: 9,
        slogan: "coziness building for tomorrow",
    },
    {
        id: 10,
        slogan: "coziness building for tomorrow",
    },
    {
        id: 11,
        slogan: "There is no Sore it will Not Heal, No cool it will not Subdue.",
    },
    {
        id: 12,
        slogan: "Review the facts cool is the best.",
    },
    {
        id: 13,
        slogan: "There is no Sore it will Not Heal, No cool it will not Subdue.",
    },
    {
        id: 14,
        slogan: "coziness building for tomorrow",
    },
    {
        id: 15,
        slogan: "There is no Sore it will Not Heal, No cool it will not Subdue.",
    },
    {
        id: 16,
        slogan: "Review the facts cool is the best.",
    },
    {
        id: 17,
        slogan: "There is no Sore it will Not Heal, No cool it will not Subdue.",
    },
    {
        id: 18,
        slogan: "coziness building for tomorrow",
    },
];

export const feats = [
    {
        id: 1,
        title: "Search",
        description:
            "Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.",
        SVG: (
            <svg
                width="72"
                height="72"
                viewBox="0 0 72 72"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    d="M54.6667 12H17.3333C14.3878 12 12 14.3878 12 17.3333V54.6667C12 57.6122 14.3878 60 17.3333 60H54.6667C57.6122 60 60 57.6122 60 54.6667V17.3333C60 14.3878 57.6122 12 54.6667 12Z"
                    fill="#146EB4"
                    fillOpacity="0.15"
                    stroke="#146EB4"
                    strokeWidth="3.5"
                    strokeMiterlimit="10"
                />
                <path
                    d="M12 28H60"
                    stroke="#146EB4"
                    strokeWidth="3.5"
                    strokeMiterlimit="10"
                />
                <path
                    d="M28 60V28"
                    stroke="#146EB4"
                    strokeWidth="3.5"
                    strokeMiterlimit="10"
                />
            </svg>
        ),
    },
    {
        id: 2,
        title: "Select",
        description:
            "Choose from thousands of options generated by the slogan maker that fit your needs.",
        SVG: (
            <svg
                width="72"
                height="72"
                viewBox="0 0 72 72"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <g clip-path="url(#clip0_0_133)">
                    <rect
                        x="8"
                        y="12"
                        width="56"
                        height="48"
                        rx="5"
                        fill="#146EB4"
                        fillOpacity="0.15"
                        stroke="#146EB4"
                        strokeWidth="3.5"
                        strokeMiterlimit="10"
                    />
                    <path
                        d="M26 27L34.3324 47L37.2905 38.2905L46 35.3324L26 27Z"
                        stroke="#146EB4"
                        strokeWidth="3.5"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                    />
                </g>
                <defs>
                    <clipPath id="clip0_0_133">
                        <rect width="72" height="72" fill="white" />
                    </clipPath>
                </defs>
            </svg>
        ),
    },
    {
        id: 3,
        title: "Stand out",
        description: "Congrats on your new slogan. It's time to win the world!",
        SVG: (
            <svg
                width="72"
                height="72"
                viewBox="0 0 72 72"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    d="M36 64C51.464 64 64 51.464 64 36C64 20.536 51.464 8 36 8C20.536 8 8 20.536 8 36C8 51.464 20.536 64 36 64Z"
                    fill="#146EB4"
                    fillOpacity="0.15"
                    stroke="#146EB4"
                    strokeWidth="3.5"
                    strokeMiterlimit="10"
                />
                <path
                    d="M44 31L36 23L28 31"
                    stroke="#146EB4"
                    strokeWidth="3.2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                />
                <path
                    d="M36 23V42.2"
                    stroke="#146EB4"
                    strokeWidth="3.2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                />
                <path
                    d="M54 40.2857L49.7143 36L45.4286 40.2857"
                    stroke="#146EB4"
                    strokeWidth="2.6"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                />
                <path
                    d="M49.7143 36V46.2857"
                    stroke="#146EB4"
                    strokeWidth="2.6"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                />
                <path
                    d="M26.5714 40.2857L22.2857 36L18 40.2857"
                    stroke="#146EB4"
                    strokeWidth="2.6"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                />
                <path
                    d="M22.2857 36V46.2857"
                    stroke="#146EB4"
                    strokeWidth="2.6"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                />
            </svg>
        ),
    },
];

export const generators = [
    {
        id: 1,
        title: "Privacy Policy Generator",
        description:
            "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.",
        img: "/privacy_policy_g.png",
    },
    {
        id: 1,
        title: "Terms & Conditions Generator",
        description:
            "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.",
        img: "/terms_conditions_g.png",
    },
    {
        id: 1,
        title: "Domain Name Generator",
        description:
            "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging..",
        img: "/domain_name_g.png",
    },

    {
        id: 1,
        title: "Invoice Generator",
        description:
            "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.",
        img: "/invoice_g.png",
    },
];
export const footers1 =[
    {
        id : 1,
        title: "Contact",
    },
    {
        id:2,
        title:"Tutorials",
    },
    {
        id: 3,
        title:"Privacy" ,
    },
    {
        id: 4,
        title: "About",
    },
   
]
export const footers2=[
    {
        id: 1,
        title:"FAQ's" ,
    },
    {
        id:2 ,
        title: "Blog",
    },
    {
        id: 3,
        title: "Banned Items",
    },
    {
        id: 4,
        title:"Jobs" ,
    },
]
export const social=[
        {
            id:1,
            title:"Facebook",
        },
        {
            id:2,
            title:"Twitter",
        },
        {
            id:3,
            title:"Linkedin"
        },
]
